### PR TITLE
Extend to harvest url and 302 gets

### PR DESCRIPTION
**Pull request by LJBabbage**
# What and why?
This PR adds a havest process to allow dynamic hyperlinks to be used. ( in this scenario case_id, would not be the same, so we can't hard coded a url into the request file). It also introduces a 302 get assert, so we don't have to follow redirects. These 2 pieces combined allow eq redirects in frontstage to be tested

# How to test?
The easiest way to test it is through concourse, I have even left the performance branch pointing at latest (N.B someone might change it back if this review hangs around)(https://concourse.rmrasbs.gcp.onsdigital.uk/teams/development/pipelines/performance/jobs/deploy-locust/builds/29#L668787b2:2) you can find a successful run with the update from this PR in the folder 24-07-08-06-21 on performance

You can test it locally if you want, but the repo has become cumbersome to do so (well before this PR). This PR from Mark is useful https://github.com/ONSdigital/ras-rm-performance-tests/pull/26 (i.e the exports and the pipfile, bs4 needs to be added to it) 
When it comes to vars they are a bit all over the place when used locally

```requests_file = '/mnt/locust/' + os.getenv('requests_file')``` should just be ```requests_file ='requests.json'```

anywhere /mnt/locust/ is used, just delete it 

```config = json.load(open("/mnt/locust/collection-exercise-config.json")) ```

becomes 

```config = json.load(open("collection-exercise-config.json"))```

and in the requests.json file the assert text for eq can be shortened to ```session?token=```

# Trello

### CODE REVIEW

**Comment by pricem14pc** [comment]
The response for the new requests are being captured individually (i.e. for each case, party and survey code combination). We'd need these grouped/aggregated for the request pattern or it's too fine grained for analysing the results.
e.g. something like
```
/surveys/access-survey?case_id={case_id}&ci_type=EQ&business_party_id={party_id}&survey_short_name={short_code}
```
and not
```
/surveys/access-survey?case_id=c9e4a8e7-c3c0-4eee-bc79-01d20d1eec87&ci_type=EQ&business_party_id=bd5fdf98-6160-47a4-a988-f039644101f7&survey_short_name=QBS
/surveys/access-survey?case_id=dd409dcc-1a56-4828-a620-4d4a127a5d16&ci_type=EQ&business_party_id=d136ac17-b7a4-44ba-8d62-73da8685d7b7&survey_short_name=QBS
/surveys/access-survey?case_id=e24939eb-2df1-4261-a5d8-21918ea5f4d8&ci_type=EQ&business_party_id=769b8017-5cba-4cd1-ba97-1e4a34c80d2e&survey_short_name=QBS
/surveys/access-survey?case_id=f80597a9-a61a-4cea-aa1a-6321350c8aff&ci_type=EQ&business_party_id=7336c60d-a4aa-4ccd-aeff-66969ade3ec6&survey_short_name=QBS
```
Locust allows us to group similar requests by `name` https://docs.locust.io/en/stable/writing-a-locustfile.html#grouping-requests

**Comment by LJBabbage** [comment]
> The response for the new requests are being captured individually (i.e. for each case, party and survey code combination). We'd need these grouped/aggregated for the request pattern or it's too fine grained for analysing the results. e.g. something like
> 
> ```
> /surveys/access-survey?case_id={case_id}&ci_type=EQ&business_party_id={party_id}&survey_short_name={short_code}
> ```
> 
> and not
> 
> ```
> /surveys/access-survey?case_id=c9e4a8e7-c3c0-4eee-bc79-01d20d1eec87&ci_type=EQ&business_party_id=bd5fdf98-6160-47a4-a988-f039644101f7&survey_short_name=QBS
> /surveys/access-survey?case_id=dd409dcc-1a56-4828-a620-4d4a127a5d16&ci_type=EQ&business_party_id=d136ac17-b7a4-44ba-8d62-73da8685d7b7&survey_short_name=QBS
> /surveys/access-survey?case_id=e24939eb-2df1-4261-a5d8-21918ea5f4d8&ci_type=EQ&business_party_id=769b8017-5cba-4cd1-ba97-1e4a34c80d2e&survey_short_name=QBS
> /surveys/access-survey?case_id=f80597a9-a61a-4cea-aa1a-6321350c8aff&ci_type=EQ&business_party_id=7336c60d-a4aa-4ccd-aeff-66969ade3ec6&survey_short_name=QBS
> ```
> 
> Locust allows us to group similar requests by `name` https://docs.locust.io/en/stable/writing-a-locustfile.html#grouping-requests

Now that is interest and not something I knew about, good spot

**Review by pricem14pc — APPROVED** [review]
Happy this is doing what we need and is a good approach. If we need to pull other values (other than a link URL) from the DOM then we can make it more generic then 👍

**Review by matthew-robinson-ons — APPROVED** [review]
Can see the performance tests have been running on "latest" for a few days now. The changes to the average response time across the percentiles looks good. Have also read through the information around the number of current locust users and think this seems appropriate with the current set up.

**Pull request merged**
